blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Questions and Help
    url: https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/discussions
    about: This issue tracker is not for support questions. Please refer to our Discussions.
  - name: ğŸ’¬ Homebridge Reddit
    url: https://www.reddit.com/r/homebridge/
    about: A place to discuss Homebridge, get help with it, ask questions about it, post plugins, and more.
  - name: â” Homebridge Discord Community
    url: https://discord.gg/kqNCe2D
    about: A place to discuss and collaborate with other Homebridge users and developers.
